--- #YAML:1.0
name:               WWW-Mechanize-Plugin-Cache
version:            0.06
abstract:           Automatic request caching for WWW::Mechanize::Pluggable
author:
    - Joe McMahon <mcmahon@yahoo-inc.com >
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Cache::FileCache:     0
    Class::Accessor::Fast:  0
    Data::Dump::Streamer:  0
    Test::Exception:      0
    Test::More:           0
    WWW::Mechanize::Pluggable:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
